// var day = document.getElementById('day')
// var month = document.getElementById('month')
// var hours = document.getElementById('hours')
// var minutes = document.getElementById('minutes')
// var second = document.getElementById('second')
// var dayName=["Sun",'Mon',"Tues",'Wed','Thurs','Fir','Sat']

// setInterval (function(){
    
//     var cuenntDate = new Date();
//     var cuennthours = cuenntDate.getHours();
    
//     day.innerText=cuenntDate.getDay(dayName);    
//     month.innerText=cuenntDate.getMonth();    
//     hours.innerText=cuenntDate.getHours();    
//     minutes.innerText=cuenntDate.getMinutes();    
//     second.innerText=cuenntDate.getSeconds();    
// },1100);






// var now = new Date();
// var bd = new Date( "4/19/1997");
// var Millesecond = now.getTime();
// var bdMillesecond = bd.getTime();

// var diff = Millesecond - bdMillesecond ;

// console.log(" millesecond=>",diff);
// console.log("second =>",Math.round(diff/1000));
// console.log("Minutes =>",Math.round(diff/1000/60));
// console.log("Hour =>",Math.round(diff/1000/60/24));
// console.log("months =>",Math.round(diff/1000/60/24/30));
// console.log("Year =>",Math.round(diff/1000/60/24/30/12));


